import { type NextPage } from "next";
import Head from "next/head";

import { signIn, signOut, useSession } from "next-auth/react";
import NavBar from "../components/Nav/NavBar";
import MainGrid from "../components/Grid/Grid";

import { api } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>81 Posts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-zinc-800">
        <NavBar />
        <div className="flex justify-center">
          <MainGrid />
        </div>
      </main>
    </>
  );
};

export default Home;
